matrix-org/matrix.to

src/components/HomePage.js
Fixes https://github.com/vector-im/vector-web/issues/2389
This adds NaChat without a logo. I didn't see any logo but maybe I just missed it. cc @Ralith
=> Add NaChat

src/components/HomePage.js
Only the first hashtag was being replaced, which meant that anything after another hashtag wouldn't be sent to the server.
=> Fix matrix-static URLs for aliases with hashtags

src/components/HomePage.js
New Vector is the current author of Riot now that Vector Creations has been dissolved. Using the new company name should be less confusing, as it will match the company name shown on many other pages about Riot.
I am not yet an expert on the company history myself, but the company changes were [recently discussed](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1540045274572566XYfoR:matrix.org) in #matrix:matrix.org where @ara4n [agreed](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1540046177575402tcVMD:matrix.org) that this is what happened.
=> Update Riot author to New Vector

README.md
Had no idea any related rooms existed until today
Also changes an old Jira link to the new GitHub issue
=> Add note about #matrix.to:riot.ovh

README.md
Just tried omitting the #/ part from example matrix.to links and it led to an attempt to open `atrix:matrix.org` in case of using a room alias and 404 for room ID and user ID. Which I believe is a good thing anyway, so just updating documentation.
=> #/ is in fact mandatory

.gitignore, .storybook/preview.js, README.md, src/App.scss, src/components/Avatar.scss, src/components/Avatar.stories.tsx, src/components/Avatar.tsx, src/components/EventPreview.tsx, src/components/InviteTile.scss, src/components/InviteTile.stories.tsx, src/components/InviteTile.tsx, src/components/LinkButton.tsx, src/components/MatrixTile.tsx, src/components/RoomPreview.scss, src/components/RoomPreview.tsx, src/components/Tile.scss, src/components/UserPreview.scss, src/components/UserPreview.tsx, src/contexts/ClientContext.ts
Adds visual components for:
- Users
- Rooms
- Events
And it adds a reducer to track the matrix servers which matrix.to is allowed to contact.
Related to: https://github.com/matrix-org/matrix.to/issues/77
Preview here: https://matrix-to-storybook.jorikschellekens.vercel.app
=> Add preview components

src/components/CreateLinkTile.tsx
fixes: https://github.com/matrix-org/matrix.to/issues/111
Validating only on blur blocked enter to submit from working if formik had marked a field as invalid on a prior blur.
Validate on change had been disabled because the input error was being displayed too early, however changes in the logic for when the error message is displayed due to the design review resolved this issue.
=> Fix enter to submit behaviour

src/matrix-cypher/schemas/EventSchema.ts, src/matrix-cypher/schemas/PublicRoomsSchema.ts, src/matrix-cypher/schemas/RoomAliasSchema.ts, src/matrix-cypher/schemas/UserSchema.ts, src/matrix-cypher/schemas/WellKnownSchema.ts
The schemas are a little too strict. This pr future proofs them a little bit by being lenient towards having extra non-specified fields present in the root of each schema. This technically allows the typed objects to have any keys but those key object pairs that are specified in the schema are still strictly required.
fixes: #114
=> Future proof schemas by making them nonstrict

src/parser/parser.ts
fixes: #62
fixes: #113
Because of the slightly more complex url parsing of the new matrix.to we can accept slashes in the identifiers.
Room aliases and room ids are simply considered opaque strings and therefore it is valid for them to be empty strings.
Please do check these carefully, I'm a little worried they may be too leniant.
https://matrix.org/docs/spec/appendices#identifier-grammar
=> Make identifier regexes closer to the spec

src/components/CreateLinkTile.tsx
The link was making it hard to copy the invite without using the button on desktop. An alternative option could have been to reduce the link bounding box but it's awkward to do. Since the link was simply an easter egg to make debugging a little easier I see no harm in removing it.
fixes: #116
=> Remove link around generated invite

src/clients/Element.io.ts, src/components/HomeserverOptions.stories.tsx, src/components/InviteTile.stories.tsx, src/components/LinkPreview.tsx, src/parser/parser.ts, src/parser/types.ts
fixes: #147
This passes all of the original params through to the client. This is valid except perhaps in the case of the sharer param. Though I do see a use for this param for the clients it could be seen as leaking personal information to the HS.
=> Pass args to clients

src/components/Footer.tsx
In the footer there's a link to add clients to the tree of this
repository, which pointed to a branch that did not exist in the
repository anymore. As such GitHub rendered a 404. This change points to
the footer URL to the `main` branch, which should exist as it's the
default branch for this project.
=> fix: Update footer URL path to existing branch

src/open/clients/Nheko.js
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
This is maybe a bit of an ugly workaround, since it basically only implements this for Nheko, but I think this may be a good start and it can be generalized at a later point? It works in my local testing and in the future, we may want to not have this in the client section but instead have a big continue button at the top and the client commands only as a fallback. But some design team would need to look at that and for now this works pretty well.
=> Allow deeplinking into Nheko via matrix: scheme

src/open/ClientView.js, src/open/ClientViewModel.js
(but keep the other cleanups we did in there)
=> Undo fix for #201 as app.element.io uses mobile page & smart app banners

src/open/clients/Element.js
According to [RFC3986 section 3.5](https://www.rfc-editor.org/rfc/rfc3986), only certain values are legal in the fragment. # in particular isn't one of them - its not a "pchar", but this is a character that appears in room names.
This seems to cause element:// urls to fail to load Element on OS X; it might cause issues elsewhere as well.
It shouldn't hurt to escape other, otherwise legal characters in the fragment such as @ and :.
Fixes https://github.com/vector-im/element-web/issues/17446
Fixes https://github.com/matrix-org/matrix.to/issues/230
=> Apply URL encoding to the fragmentPath

src/open/clients/Element.js
#248 introduced url encoding for the android element:// link but this caused a regression because the encoded url cannot be picked up by android's filters.  See #259 
This returns the android url to its previous form which still worked.
Fixes #259
=> Remove url encoding from android element:// links

README.md
Avoids confusion for people trying to make links lead to their own instance.
The wording "our list" should help people realize that they can self-host matrix.to and change the whitelist.
=> Mention trusted web instances

scripts/build.js, src/Link.js, src/RootViewModel.js, src/open/ClientViewModel.js, src/preview/HomeServer.js, src/utils/TemplateView.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> Replace deprecated String.prototype.substr()

index.html
Add embeds to make matrix invite links more obvious on twitter.
Links to matrix rooms are easily lost on twitter, especially if the same tweet includes a link to a site with embed support, example:
Add meta tags for twitter so that if matrix.to links are posted first, they will be used for the embed, this will make them more obvious / appealing to click, this PR will result in tweets with matrix.to links looking like the following instead:
The title/description is just pulled from matrix.org, maintainers may want to make this something matrix.to specific or choose something that better represents the platform in this context.
=> Add twitter embed meta tags

README.md
matrix.to has a list of trusted web-based Matrix clients to redirect to. The README contained a link pointing to this `trustedWebInstances` allowlist array *at a specific commit*. This information became outdated when we updated the list.
This PR changes the link to always point to the latest commit, with some direction about where to look. It will also become outdated if we move the file or change the variable name, but that's less likely to happen than pushing a new commit.
=> Update link to trusted web clients in the README and attempt to future-proof

src/open/clients/Element.js
Add `app.gitter.im` as a trusted web instance
`app.gitter.im` is the Gitter branded Element instance since Gitter full migrated to Matrix ([context](https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/))
Usage:
```
https://matrix.to/#/#gitter_gitter:gitter.im?web-instance[element.io]=app.gitter.im
```
=> Add `app.gitter.im` as a trusted web instance

images/client-icons/cinny.svg, src/open/clients/Cinny.js, src/open/clients/cinny.js, src/open/clients/index.js
This PR adds the Cinny client.
Basically a cleaner version of #234.
I am not sure about the copyright of the SVG, it is licensed under `Creative Commons Attribution 4.0 International License` so it's okay to use, I just don't know where to put the attribution.
=> Add the Cinny client

src/open/clients/Element.js
The previous link now leads to a page that says "Contact Sales".
=> Fix desktop Element download link

.gitignore, scripts/build.js, src/open/clients/Element.js
This PR makes 2 changes:
- Add Element X app IDs to Element's client definition.
- Tidy up the generated [site association file](https://developer.apple.com/documentation/xcode/supporting-associated-domains)
- The empty `apps` array isn't expected for `applinks` definition so I removed it.
- The `webcredentials` definition is to support password filling on the site, which as far as I understand it, matrix.to doesn't have any login form, so I removed this too.
The generated file looks like this after these changes:
```json
{
"applinks": {
"details": {
"appIDs": [
"7J4U792NQT.im.vector.app",
"7J4U792NQT.io.element.elementx",
"7J4U792NQT.io.element.elementx.nightly",
"7J4U792NQT.io.element.elementx.pr"
],
"components": [
{
"#": "/*"
}
]
}
}
}
```
=> Add Element X iOS entries in the apple-app-site-association.

scripts/build.js
It seems the file had an error where `details` was a single object instead of an array of objects. This PR fixes it to match the documentation: https://developer.apple.com/documentation/bundleresources/applinks
**Generated file:**
```
{
"applinks": {
"details": [
{
"appIDs": [
"7J4U792NQT.im.vector.app",
"7J4U792NQT.io.element.elementx",
"7J4U792NQT.io.element.elementx.nightly",
"7J4U792NQT.io.element.elementx.pr"
],
"components": [
{
"#": "/*",
"comment": "Only open urls with a fragment, so you can still create links"
}
]
}
]
}
}
```
=> Fix the apple-app-site-association file.
