matrix-org/matrix.to

README.md
src/components/HomePage.js

Fixes https://github.com/vector-im/vector-web/issues/1658

Support Room ID links

---

src/components/HomePage.js

Fixes https://github.com/vector-im/vector-web/issues/2390

Remove Tensor2

---

package.json

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

make development cross-platform compatible

---

src/components/HomePage.js

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

remove duplicate value fail, this.state.value does not exist.

---

img/matrix-badge.svg

See #20
NOTE: this commit only adds the (improvable) badge, but does not
show it yet on the page

Add matrix:chat badge

---

img/org.gnome.Fractal.svg
src/components/HomePage.js

[Fractal](https://gitlab.gnome.org/World/fractal) is a GTK+ Matrix client.

Added Fractal

---

src/components/HomePage.js

Delete deprecated matrix console app

---

public/index.html
src/_color-scheme.scss
src/index.scss

Sets the basic colour scheme and sets styling for some style for h1.

Configure the color scheme

---

.storybook/main.js
.storybook/preview.js
docs/developers.md
package.json
src/components/Button.stories.tsx
src/components/CreateLinkTile.stories.tsx
src/components/Input.stories.tsx
src/components/MatrixTile.stories.tsx
src/components/TextButton.stories.tsx
src/components/Tile.stories.tsx
src/index.scss
tsconfig.json
yarn.lock

fixes: https://github.com/matrix-org/matrix.to/issues/98
I've configured story book for all components.
I've configured the accessibility, code, viewport, accessibility and knobs extensions as global decorators.
I've also added a community addon that displays figma designs which is maintained by the developers of figma themselves.
Overall I'm very impressed by this and it's made working on individual components so much faster.

Add storybook

---

src/components/Avatar.tsx
src/components/LinkPreview.tsx
src/utils/cypher-wrapper.ts

Adds better fallback metadata depends on https://github.com/matrix-org/matrix.to/pull/103

Implement better fallbacks

---

src/components/DefaultPreview.scss
src/components/LinkPreview.tsx
src/components/StyledCheckbox.tsx
src/components/Toggle.tsx
src/components/UserPreview.tsx
src/contexts/HSContext.ts
src/utils/getHS.ts

Display sharer info on invites
[Example](https://matrix-to-static-p0al8wy43.vercel.app/#/#element-dev:matrix.org?sharer=@jorik:matrix.org)

Add sharer info

---

src/index.scss

Fixes https://github.com/matrix-org/matrix.to/issues/121

Add more sans fonts

---

src/components/Avatar.scss
src/components/Avatar.tsx
src/components/GroupPreview.scss
src/components/GroupPreview.tsx
src/components/LinkPreview.tsx
src/matrix-cypher/matrix-cypher.ts
src/matrix-cypher/schemas/GroupSchema.ts
src/utils/cypher-wrapper.ts

Realised I'd overlooked groups a little. Unfortunately the groups api is hidden behind an access token even for public groups.

Add rudimentary group support

---

src/clients/Fractal.tsx
src/components/ClientTile.tsx

Updates the fractal description and also hides the 'copy invite' button if there's nothing to copy
fixes: #115
fixes: #125

Update fractal description

---

src/components/Avatar.tsx
src/components/GroupPreview.tsx
src/components/LinkPreview.tsx
src/components/UserPreview.tsx
src/matrix-cypher/matrix-cypher.ts
src/utils/cypher-wrapper.ts
src/utils/getHS.ts

Prevents matrix.to from downloading huge images
fixes: #123

Use thumbnails api instead of mxc download

---

src/App.tsx

Remove the existentialist crisis

---

package.json
src/index.scss
src/index.tsx
yarn.lock

Fixes https://github.com/matrix-org/matrix.to/issues/120

Hide focus ring for mouse users

---

src/open/ClientListView.js
src/open/ClientView.js
src/open/ClientViewModel.js
src/preview/PreviewView.js
src/utils/TemplateView.js

Show both open and install options when deeplink for native app is https link

---

images-nohash/matrix-badge.svg
package.json
scripts/build.js

Bring back badge

---

src/open/clients/Fluffychat.js

Famous last words: "I can quickly change this in the GitHub editor. No need for an IDE with lints for Javascript or auto formatting. I can do this!"

Add deep link for FluffyChat Android and iOS

---

src/open/clients/Quaternion.js

Update metadata about Quatermion

---

src/open/clients/Fluffychat.js
src/open/clients/Nheko.js
src/open/clients/Quaternion.js

Adds macOS and Windows install links for Quaternion and Nheko
Adds F-Droid button for Fluffychat
Fixes https://github.com/matrix-org/matrix.to/issues/243

Add new install links for Quaternion, Nheko, and FluffyChat

---

src/open/clients/Element.js

Should fix joining rooms by roomid via matrix.to.
Fixes https://github.com/matrix-org/matrix.to/issues/235
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

Properly pass vias to Element clients

---

images/client-icons/thunderbird.svg
src/open/clients/Thunderbird.js
src/open/clients/index.js

Add Thunderbird as a client selection.
CC @clokep

Add Thunderbird

---

images/client-icons/syphon.svg
src/open/clients/Syphon.js
src/open/clients/index.js

Adding [Syphon](https://syphon.org) as experimental client selection as per https://github.com/syphon-org/syphon/discussions/725#discussioncomment-3628003

Add Syphon

---

images/client-icons/schildichat.svg
src/open/clients/SchildiChat.js
src/open/clients/index.js

- fixes #276
- PR will be checked by SchildiChat devs, then the PR will be marked as ready
- Compatibility of redirects were tested on Linux Desktop & Android (with the F-Droid version)
(description was updated in code)

Add SchildiChat to clients

---

src/open/clients/Element.js

Closes https://github.com/element-hq/element-meta/issues/2813

Change the Element mobile download links to Element X.

---

src/Link.js

MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/4291
Pre-disclosure: https://matrix.org/blog/2025/07/security-predisclosure/

Support v12 room IDs
